DROP TABLE USERS;

CREATE TABLE USERS (
	
	ID VARCHAR(50) NOT NULL PRIMARY KEY
	, NAME VARCHAR(250) NOT NULL
	, PASSWORD VARCHAR(50) NOT NULL

);

INSERT INTO USERS VALUES ('nts', '남택승', 'nts123');

SELECT * FROM USERS;